### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Chen-ZhengHui** [LuxLuma/-L4D2-Survivor_Legs#1]
Hello, may I ask, after I import the plug-in, the character lies on the ground, is there something WRONG with me, I hope someone can help me, thank you。
<img width="960" alt="微信图片_20220609032137" src="https://user-images.githubusercontent.com/59163170/172700833-6cdf407b-1179-4722-8320-d6c9fd71bd96.png">
<img width="397" alt="微信图片_20220609032533" src="https://user-images.githubusercontent.com/59163170/172700863-523f9b82-a347-42ac-89b2-a28e7d5eaf9f.png">
<img width="495" alt="微信图片_20220609032602" src="https://user-images.githubusercontent.com/59163170/172700879-802358ee-2f2e-46b6-bbe0-3280d80b6f91.png">

**Comment by LuxLuma** [comment]
This plugin assumes you are using vanilla survivor models, this problem is due to the model it's self.
If you are using this on listen server, I suggest making a dedicated server using **srcds** and not using any survivor modifying mods on it.

**Comment by Chen-ZhengHui** [comment]
First of all, thanks for the answer. Problem solved, I did not match the.smx and.sp versions, embarrassed... Finally, you are my hero, and I love this plugin
